server:
  port: 9882
spring:
  application:
    name: user
  datasource:
    name: goodgoodsrs
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goodgoodsrs?serverTimezone=UTC
    username: root
    password: root
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #nacos
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        name: dev
        file-extension: yaml


mybatis:
  type-aliases-package: com.sxl.goodgoodsrs.api.user.model


