server:
  port: 9880
spring:
  application:
    name: recommend
  datasource:
    name: goodgoodsrs
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goodgoodsrs?serverTimezone=UTC
    username: root
    password: root
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #nacos
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        namespace: public

mybatis:
  type-aliases-package: com.sxl.goodgoodsrs.api.recommend.model


